---
- name: Ansible ping module
  hosts: test_node
  vars_files: ./group_vars/all/.vault.yml

  tasks:
    - name: Ping check
      ansible.builtin.ping:

    - name: Print message
      ansible.builtin.debug:
        msg: Test complete
